### ISSUE TITLE
Opening Dropdown buttons causes the page to jump down

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#297] opened 2016-12-15 06:43 UTC
1. On iPhone go to Buttons - Dropdown Buttons.
2. Tap on a dropdown button.
3. Notice the screen jumps down to a random position.

This behaviour is not evident when the GUI source is tested on iPhone. This would suggest that the issue is with the implementation in the Docs

**Comment by dominikwilkowski** [comment] 2016-12-15 06:45
That's supposed to happen as for a11y the focus needs to move to the opened container. When that container is larger than the screen the browser scrolls it into view. All browsers have different concepts of what "scroll into view" means.

I would not consider this a bug

**Comment by justinspencer** [comment] 2016-12-15 07:01
I've attached an animated gif to try and explain.

![jump](https://cloud.githubusercontent.com/assets/936597/21214686/7e8535c6-c2f0-11e6-8f1f-f54e150a976e.gif)

**Comment by diced-dev** [comment] 2017-01-02 06:59
I've tested it in Browserstack and it seems to be functioning as intended (as Dom explained above).

There may be something strange going on with the example embedded within the docs page, but I wasn't able to duplicate what you shared above Justin.

Recommend we close this one.

**Closed** 2017-01-03 05:06 UTC
Labels: bug, docs, module: buttons
