### ISSUE TITLE
logos.less  why is there brand names in the class names and can we share when properties are the same

### ISSUE THREAD

**Issue by dowda** [WestpacCXTeam/GUI-source#166] opened 2015-12-08 02:29 UTC
why is there brand names in the class names?

see logos.less

&.logo-bom-alt {
	width: 180px;
	height: 65px;
}
&.logo-bsa-alt {
	width: 180px;
	height: 65px;
}
&.logo-wbc-alt {
	width: 180px;
	height: 65px;
}

could be

&.logo-alt{
       width: 180px;
	height: 65px;
}

cheers
Cheech

**Comment by dominikwilkowski** [comment] 2015-12-08 03:14
closing as duplicate of #165

**Closed by dominikwilkowski** 2015-12-08 03:14 UTC
Labels: question

**Comment by dowda** [comment] 2015-12-08 04:46
Hi Dom  This isn't a dup. This is about having the brand in the class

&.logo-bsa-alt  or  &.logo-bom-alt    why do we need this?


See logos.less

**Comment by dominikwilkowski** [comment] 2015-12-08 04:50
Sorry if I misunderstood.

> The symbols module gives you your current brand logo so in a multi-brand environment something like:
> `<span class="symbol symbol-logo-phone"></span>` will be the logo of whatever brand you're developing in. No HTML changes between a brand build.

> **But sometimes you want all logos like in a project like locate-us. For those we got the logos module. Those classes then have to be specific to point directly to a brand logo and don't change between brands. Still no changes between brand builds.**

The last bit is relevant for this question. If you don't have a specific class for each brand then you won't be able to know what logo you want to display.
