### ISSUE TITLE
Core - Spacing after headings.

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#206] opened 2016-03-02 10:37 UTC
We need to figure out a way to apply smarter spacing to headings. The current system sets a bottom margin which works at certain line widths but when the line widths are reduced the bottom margins and line heights need to be reduced or the typography breaks. This is similar to the 1.4 line height technique we use however there are added complexities with headings as the space around a heading depends on the size and line height of the text before and after it. The other option is to remove margins completely and use margin classes.This will allow visual designers to dictate what space should accompany a heading in any scenario.

**Comment by justinspencer** [comment] 2016-04-03 11:46
Just looked at the salesforce GUI. They don't spec headings so devs focus on semantics rather than visual hierarchy. They use helper classes to add text styling. Interesting!

**Comment by dominikwilkowski** [comment] 2016-04-03 11:50
That's what we do but we don't advertise it in the docs. I agree we should probably change that :)

**Comment by dominikwilkowski** [comment] 2016-06-01 00:18
closing as duplicate of WestpacCXTeam/GUI-source#251

**Closed by dominikwilkowski** 2016-06-01 00:18 UTC
Labels: enhancement, module: _text-styling
