### ISSUE TITLE
Tabs module jumping down page on iPhone

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#296] opened 2016-12-15 01:40 UTC
1. On iPhone go to Containers-Soft tabs.
2. Tap on a tab.
3. You will notice the whole screen jumps down to a random location on the page.

I've tested the source and this does not happen however the source page isn’t responsive so its difficult to test properly. I'd say this is an issue with the examples in Docs rather than the tabs module.

**Comment by diced-dev** [comment] 2017-01-02 07:08
I've tested it in Browserstack and it seems to be functioning as intended.

Like the dropdown buttons there may be something strange going on with the example embedded within the docs page, but I wasn't able to duplicate it.

Recommend we close this one.

**Closed** 2017-01-03 05:06 UTC
Labels: bug, docs, module: tabcordions
